### ISSUE TITLE
Updater causing PHP warning

### ISSUE THREAD

**Issue by pacmanito** [skyverge/woocommerce-shipping-estimate#31]
Found such warning in my error log:
`Warning: Creating default object from empty value in /wp-content/plugins/woocommerce-shipping-estimate/lib/skyverge/updater/class-skyverge-plugin-updater.php on line 631`

It's rather strange considering there's `if ( ! empty( $custom_icons ) )`  clause in your code.
Unfortunately I have no idea what triggered the error, as far as I remember I was not doing anything in the backend when the error appeared.

**Comment by pacmanito** [comment]
I am still getting this warning on regular basis.

**Comment by unfulvio** [comment]
thanks @pacmanito for reporting this - we identified  the problem and issue an update soon

**Comment by unfulvio** [comment]
issue should be addressed in https://github.com/skyverge/woocommerce-shipping-estimate/releases/tag/2.4.1 thanks for your patience here!

**Comment by pacmanito** [comment]
Hi, guys. I am still having the same warning in my logs. It seems to be there not as often as before, but at least once a week I see it there.
